---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sebdco1/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp inner-page.html $DEPLOYPATH
    - /bin/cp portfolio-details.html $DEPLOYPATH